name: CI

on: [push, pull_request]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - stable
          - beta
          - nightly
          - '1.41.0'
        features:
          -
          - derive
          - hmac-sha1
    steps:
      - uses: actions/checkout@v2
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.toolchain }}
          profile: minimal
          override: true
        id: toolchain
      - name: Cache Cargo registry
        uses: actions/cache@v2
        with:
          path: ~/.cargo/registry
          key: cargo-registry-${{ runner.os }}-${{ matrix.features }}-${{ hashFiles('Cargo.*') }}
          restore-keys: |
            cargo-registry-${{ runner.os }}-${{ matrix.features }}-${{ hashFiles('Cargo.*') }}
            cargo-registry-${{ runner.os }}-${{ matrix.features }}-
            cargo-registry-${{ runner.os }}-
      - name: Cache Cargo build
        uses: actions/cache@v2
        with:
          path: target
          key: cargo-build-target-${{ runner.os }}-${{ steps.toolchain.outputs.rustc_hash }}-${{ matrix.features }}-${{ hashFiles('**/Cargo.*') }}
          restore-keys: |
            cargo-build-target-${{ runner.os }}-${{ steps.toolchain.outputs.rustc_hash }}-${{ matrix.features }}-${{ hashFiles('**/Cargo.*') }}
            cargo-build-target-${{ runner.os }}-${{ steps.toolchain.outputs.rustc_hash }}-${{ matrix.features }}-
            cargo-build-target-${{ runner.os }}-${{ steps.toolchain.outputs.rustc_hash }}-
      - name: Build `oauth1-request-derive`
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --verbose --manifest-path oauth1-request-derive/Cargo.toml
      - name: Build `oauth1-request`
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --verbose --manifest-path oauth1-request/Cargo.toml --features=${{ matrix.features }}
      - name: Build `examples`
        # if: ${{ matrix.toolchain != '1.41.0' }}
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --verbose --manifest-path examples/Cargo.toml
      - name: Test `oauth1-request`
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --manifest-path oauth1-request/Cargo.toml --features=${{ matrix.features }}
      - name: Test `oauth1-request-derive`
        if: matrix.toolchain == 'nightly'
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --verbose --manifest-path oauth1-request-derive/Cargo.toml
